### ISSUE TITLE
Crash on a randomization (not on a stable release)

### ISSUE THREAD

**Issue by Erzangel** [Nifyr/A-Little-Secret-Ingredient#2] opened 2023-06-14 20:19 UTC
# Description

Tried the latest commit, 73961c9e590b44770fbc4f9ded562845efd3d69a, and got a randomization that crashes the game on title screen (right when they are supposed to say "Fire Emblem: Engage").

Tried loading the randomization through LayeredFS and through Cobalt, and both make the game crash.

I know this is not supposed to be a stable release, but sharing this at it might possibly help

Going to verify if this works with another randomization (I turned on most settings)

## Output

Here is the `Output` folder uploaded on mega.nz: https://mega.nz/file/qYoEhKqJ#zggDH9zOgPnzkY_eDarMR7LMiTDm6Z1Gz6C_-qaFXE8

**Comment by Erzangel** [comment] 2023-06-14 20:26
Other randomizations seem to work, I disabled the character size scaling setting, might have been that causing it.

**Comment by Nifyr** [comment] 2023-06-15 13:25
Yeah, slight stability issues with asset shuffles for some reason. Some combination of fields apparently results in a crash... under investigation for the time being.

**Comment by Erzangel** [comment] 2023-06-15 13:56
ouch, good luck with that! 

and once again, a million thanks for the love poured in this! never expected so many new features to release so quick, super excited about trying out different starting classes, inventory swap, etc 🙂

**Comment by Nifyr** [comment] 2023-06-16 01:07
Finally found the cause for this particular crash: It turns out that the game straight up crashes on the title screen if the protagonist's starting level is anything but 1... Fixed in newest commit. Don't hesitate to open issues if similar cases occur. 👍

**Closed as completed by Nifyr** 2023-06-16 01:07 UTC
Labels: bug
